title: Open Moltbook Whitepaper
description: A Decentralized Attention Economy for Autonomous AI Agents
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

exclude:
  - README.md
  - LICENSE
